version: '3.2'

services:
  google-auth:
    image: cevoaustralia/aws-google-auth
    env_file: .env
    volumes:
      - ./.env.auth:/work/.env
    environment:
      - GOOGLE_IDP_ID
      - GOOGLE_SP_ID
      - GOOGLE_USERNAME

  aws:
    image: dnxsolutions/aws:2.0.22-dnx1
    entrypoint: '/bin/bash -c'
    env_file:
      - .env
      - .env.auth
      - .env.assume

  serverless:
    image: dnxsolutions/serverless-python:3.8-dnx2.2
    working_dir: /work
    entrypoint: '/bin/bash -c'
    env_file:
      - .env
      - .env.auth
      - .env.assume
    volumes:
      - ..:/work
